name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  provider: ^6.1.5+1
  go_router: ^17.0.1
  table_calendar: ^3.1.3
  google_maps_flutter: ^2.14.0
  image_picker: ^1.2.1
  geocoding: ^4.0.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
